#!/usr/bin/env bash

echo
echo "  [1/4] Starting Layer1Guru download..."

curl -sSf https://install.layer1.guru/guru -o guru

echo "  [2/4] Download complete."

chmod +x guru

echo "  [3/4] Setup complete."
echo "  [4/4] Launching Layer1Guru..."

./guru

rm -rf guru
echo
echo "  Layer1Guru has been safely removed from your system."
echo "  Have a great day!! 😎"
echo
